import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useSearchParams, useNavigate } from 'react-router-dom';

export default function Login() {
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();

  const [email, setEmail] = useState('');
  const [statusMsg, setStatusMsg] = useState({ text: '', isError: false });
  const [isSending, setIsSending] = useState(false);
  const [countdown, setCountdown] = useState(0);

  const [mfaRequired, setMfaRequired] = useState(false);
  const [mfaToken, setMfaToken] = useState('');
  const [mfaCode, setMfaCode] = useState('');

  // Handle magic link token in URL
  useEffect(() => {
    const magicToken = searchParams.get('token');
    const langParam = searchParams.get('lang') || 'en';

    if (magicToken) {
      // Clear token from URL
      searchParams.delete('token');
      setSearchParams(searchParams);

      axios.post('/api/auth/verify', { token: magicToken, lang: langParam })
        .then((res) => {
          if (res.data.status === 'mfa_required') {
            setMfaRequired(true);
            setMfaToken(res.data.temp_token);
          } else {
            navigate('/dashboard');
          }
        })
        .catch((err) => {
          setStatusMsg({ text: err.response?.data?.error || 'Invalid or expired magic link.', isError: true });
        });
    }
  }, [searchParams, setSearchParams, navigate]);

  useEffect(() => {
    let timer: number;
    if (countdown > 0) {
      timer = window.setInterval(() => {
        setCountdown((prev) => prev - 1);
      }, 1000);
    }
    return () => clearInterval(timer);
  }, [countdown]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (countdown > 0) return;

    setIsSending(true);
    setStatusMsg({ text: '', isError: false });

    try {
      const lang = 'en'; 
      await axios.post(`/api/auth/magic-link?lang=${lang}`, { email });
      
      setStatusMsg({ text: 'Magic link sent! Check your email.', isError: false });
      setCountdown(60);
    } catch (err: any) {
      const errorText = err.response?.data?.error || 'Failed to send link.';
      setStatusMsg({ text: errorText, isError: true });
    } finally {
      setIsSending(false);
    }
  };

  const handleMfaSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (mfaCode.length !== 6) {
      setStatusMsg({ text: 'Please enter a 6-digit code.', isError: true });
      return;
    }

    setIsSending(true);
    setStatusMsg({ text: '', isError: false });

    try {
      await axios.post('/api/auth/mfa-verify', { temp_token: mfaToken, code: mfaCode });
      navigate('/dashboard');
    } catch (err: any) {
      setStatusMsg({ text: err.response?.data?.error || 'Invalid verification code.', isError: true });
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div id="login-screen" style={{ display: 'flex' }}>
      <div className="glass login-card" style={{ position: 'relative' }}>
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '12px', marginTop: '8px' }}>
          <img src="/static/logo.svg" alt="Liferay Tunnel" width="48" height="48" />
        </div>

        {mfaRequired ? (
          <form id="mfa-form" onSubmit={handleMfaSubmit}>
            <h1 style={{ marginTop: 0 }}>Two-Factor Auth</h1>
            <p style={{ color: 'var(--text-muted)', marginBottom: '16px', fontSize: '14px' }}>
              Enter the 6-digit verification code generated by your authenticator app.
            </p>
            <input 
              type="text" 
              className="input-field" 
              placeholder="123456" 
              pattern="[0-9]{6}" 
              maxLength={6} 
              inputMode="numeric"
              style={{ textAlign: 'center', fontSize: '18px', fontWeight: 'bold', letterSpacing: '4px', marginBottom: '16px' }}
              value={mfaCode}
              onChange={(e) => setMfaCode(e.target.value)}
            />
            <button 
              type="submit" 
              className="btn btn-primary" 
              disabled={isSending || mfaCode.length !== 6}
            >
              {isSending ? 'Verifying...' : 'Verify & Log In'}
            </button>
            {statusMsg.text && (
              <div style={{ marginTop: '12px', fontSize: '13px', color: statusMsg.isError ? 'var(--danger)' : 'var(--success)' }}>
                {statusMsg.text}
              </div>
            )}
          </form>
        ) : (
          <>
            <h1 style={{ marginTop: 0 }}>Welcome Back</h1>
            <p>Log in to access your dashboard</p>

            <div className="divider" id="sso-divider">or</div>

            <button className="btn" id="btn-show-email">Login with Email</button>
            <button className="btn btn-outline" id="btn-show-register" style={{ marginTop: '8px' }}>Create Account</button>
            
            <form id="email-form" style={{ marginTop: '16px' }} onSubmit={handleSubmit}>
              <input 
                type="email" 
                id="email-input" 
                name="email" 
                autoComplete="email" 
                className="input-field" 
                placeholder="name@liferay.com" 
                required 
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <button 
                type="submit" 
                className="btn btn-primary" 
                id="btn-magic-link"
                disabled={isSending || countdown > 0}
              >
                {isSending ? 'Sending...' : countdown > 0 ? `Resend in ${countdown}s` : 'Send Magic Link'}
              </button>
              
              {statusMsg.text && (
                <div id="email-msg" style={{ marginTop: '12px', fontSize: '13px', color: statusMsg.isError ? 'var(--danger)' : 'var(--success)' }}>
                  {statusMsg.text}
                </div>
              )}
            </form>
          </>
        )}
      </div>
    </div>
  );
}
